# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabco_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='atendee_limit',
        ),
        migrations.AddField(
            model_name='event',
            name='attendee_limit',
            field=models.IntegerField(default=0),
        ),
    ]
