# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabco_project', '0003_auto_20160827_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_venue',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cabco_project.Venue'),
            preserve_default=False,
        ),
    ]
